FROM python:3.9

LABEL version="0.1.0"
LABEL description="Docker image for python with pandas"
LABEL maintainer="Sahand Vahidnia <@sahandv>"


COPY requirements.txt /
# Install dependencies
RUN pip install -r /requirements.txt 


CMD ["/bin/bash"]